MyTestProject24/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyTestProject24.Models
{
    public class User
    {
        public int UserID { get; set; }

        public string Name { get; set; }

        public string Hometown { get; set; }

        public string Information { get; set; }

        [Required]
        public string Avatar { get; set; }

        virtual public List<Post> Posts { get; set; } 

        virtual public List<Track> FavoriteSongs { get; set; }
    }
}

MyTestProject24/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyTestProject24.DAL;
using MyTestProject24.Models;
using System.Threading;

namespace MyTestProject24.Controllers
{
    public class AuthorsController : Controller
    {
        private UserContext db = new UserContext();
        private static int currentId;

        // GET: Authors
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,Name,Photo")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                currentId = author.AuthorID;
                Thread t = new Thread(FillAlbums);
                t.Start();
                return RedirectToAction("Profile", new { id = author.AuthorID});
            }



            return RedirectToAction("Profile", new { id = author.AuthorID });
        }


        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Profile(int id)
        {
            var author = db.Authors.Find(id);
            if (author == null) return HttpNotFound();
            if (author.Information == null)
            {
                author.Information = WebSearcher.GetArtistInformation(author.Name, 1);
                db.SaveChanges();
            }
            return View(author);
        }

        static void FillAlbums()
        {
            int id = currentId; 
            UserContext db = new UserContext();
            string authorName = db.Authors.Find(id).Name;
            List<string> authorAlbums = WebSearcher.GetAlbumsOfArtist(authorName);
            foreach(var album in authorAlbums)
            {
                Album currentAlbum = new Album();
                currentAlbum.AuthorID = id;
                currentAlbum.Name = album;
                currentAlbum.Image = WebSearcher.GetImageOfAlbum(authorName, album);

                db.Albums.Add(currentAlbum);
                db.SaveChanges();

                //IT WAS HIDDEN
                List<string> trackList = WebSearcher.GetTrackListOfAlbum(authorName, album);
                
                foreach(var track in trackList)
                {
                    Track currentTrack = new Track();
                    currentTrack.AlbumID = currentAlbum.AlbumID;
                    currentTrack.Author = db.Authors.Find(id);
                    currentTrack.Name = track;
                    currentTrack.Lyrics = WebSearcher.GetLyricsOfSong(authorName, track);
                    db.Tracks.Add(currentTrack);
                    db.SaveChanges();
                }
                //IT WAS HIDDEN
                if (db.Albums.Find(currentAlbum.AlbumID).Tracks == null)
                {
                    db.Albums.Remove(currentAlbum);
                    db.SaveChanges();
                }
            }

        }        


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyTestProject24/Controllers/UserController.cs
using MyTestProject24.DAL;
using MyTestProject24.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyTestProject24.Controllers
{
    public class UserController : Controller
    {
        UserRepository db = new UserRepository();
        //Repository<Post> dbPost = new Repository<Post>();
        // GET: UserList
        [Route("users")]
        public ActionResult Index()
        {
            foreach (var item in db.GetAll())
            {
                if (item == null || item.Avatar == null || item.Name == null)
                {
                    db.Remove(item.UserID);
                    db.SaveChanges();
                }
            }
            return View(db.GetAll());
        }

        //GET: Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: Create
        [HttpPost]
        public ActionResult Create(User user)
        {
            db.Add(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET : User/Delete/id
        [Route("user/delete/{id:int}")]
        public ActionResult Delete(int id)
        {
            if (db.Get(id) == null)
                return HttpNotFound();
            db.Remove(id);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Route("prof/{id:int}")]
        public ActionResult Prof(int id)
        {
            var user = db.Get(id);
            if(user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [Route("Profile/{id:int}")]
        public ActionResult Profile(int id)
        {
            var user = db.Get(id);
            if(user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        public ActionResult Search(string searchString)
        {
            if (searchString == null)
            {
                return HttpNotFound();
            }

            var userList = db.GetAll().Where(m => m.Name.ToUpper().Contains(searchString.ToUpper()));
            ViewBag.authorList = db.context.Authors.Where(m => m.Name.ToUpper().Contains(searchString.ToUpper())).ToList();
            return View(userList);
        }


    }
}

MyTestProject24/Views/User/Create.cshtml
@model MyTestProject24.Models.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hometown, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hometown, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hometown, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyTestProject24/Views/User/Index.cshtml
@model IEnumerable<MyTestProject24.Models.User>


@{
    ViewBag.Title = "Index";
}



<h2></h2>
@Html.ActionLink("Create new Person", "Create")
<h3>People:</h3>


@foreach (var item in Model)
{
    <nav class="navbar" style="box-shadow: 0px 1px 2px rgba(0,0,0,0.6)">
        <div class="container-fluid">
                <div class="row">

                    <div class="col-md-1">
                        <img alt="Brand" src=@item.Avatar.ToString() width="64" height="64">
                    </div>

                    <div class="col-md-10">
                        <h4>  
                            @Html.ActionLink(@item.Name, "Profile",
                                new { id = item.UserID },
                                new { @class = "classname" })
                        </h4>
                    </div>

                    <div class="col-md-1">
                        <br />
                        @Html.ActionLink(".", "Delete", new { id = item.UserID }, new { @class = "glyphicon glyphicon-remove-circle" })
                    </div>

                </div>
        </div>
    </nav>


}




    

MyTestProject24/Views/User/Profile.cshtml
@model MyTestProject24.Models.User

@{
    ViewBag.Title = Model.Name;
}
<div><br /></div>
<div class="row">
    <div class="col-md-3"> <img src=@Model.Avatar.ToString() alt="Photo" height="200" width="200" /> </div>
    <div class="col-md-4">
        <h3><p>Name : @Model.Name</p></h3>
        <h3><p>Homewtown : @Model.Hometown</p></h3>
    </div>
</div>

<h5> @Model.Name listened: </h5>
@foreach (var post in Model.Posts)
{
    <div>
        <p>
            
            <h8>@post.DataTime.ToShortDateString()</h8>
            <p>
                <h5>@post.Text</h5>
            </p>
        </p>
    </div>
}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserID })
    @Html.ActionLink("Back to List", "Index")
</p>

MyTestProject24/Views/User/Search.cshtml
@model IEnumerable<MyTestProject24.Models.User>
@{
    ViewBag.Title = "Search";
}

<h2>We found for you:</h2>


<h3>Authors:</h3>
@if (ViewBag.authorList.Count == 0)
{
    <p>No authors</p>
}
@foreach (var author in ViewBag.authorList)
{
    <nav class="navbar" style="box-shadow: 0px 1px 2px rgba(0,0,0,0.6)">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-1">
                    <img alt="Brand" src=@author.Photo.ToString() width="64" height="64">
                </div>

                <div class="col-md-10">
                    <h4>
                        @{
                            string s = author.Name;
                            int authorId = author.AuthorID;
                        }
                        @Html.ActionLink(@s, "Profile", "Authors", new { id = authorId }, null)
                    </h4>
                </div>

            </div>
        </div>
    </nav>
}



<h3>Users:</h3>
@if (Model.Count() == 0)
{
    <p>No users</p>
}
@foreach (var item in Model)
{
    <nav class="navbar" style="box-shadow: 0px 1px 2px rgba(0,0,0,0.6)">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-1">
                    <img alt="Brand" src=@item.Avatar.ToString() width="64" height="64">
                </div>

                <div class="col-md-10">
                    <h4>
                        @Html.ActionLink(@item.Name, "Profile",
                                new { id = item.UserID },
                                new { @class = "classname" })
                    </h4>
                </div>

            </div>
        </div>
    </nav>
}

MyTestProject24/Views/User/User.cshtml
@model MyTestProject24.Models.User

@{
    ViewBag.Title = "User";
}

<h2>User</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hometown)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hometown)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avatar)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserID }) |
    @Html.ActionLink("Back to List", "Index")
</p>