MyTestProject24/Models/Author.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyTestProject24.Models
{
    public class Author
    {
        public int AuthorID { get; set; }

        [Required()]
        public string Name { get; set; }

        [Required()]
        public string Photo { get; set; }

        public string Information { get; set; }

        virtual public List<Track> Tracks { get; set; }

        virtual public List<Album> Albums { get; set; }
    }
}

MyTestProject24/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyTestProject24.DAL;
using MyTestProject24.Models;

namespace MyTestProject24.Controllers
{
    public class AlbumsController : Controller
    {
        private UserContext db = new UserContext();

        // GET: Albums
        public ActionResult Index()
        {
            var albums = db.Albums.Include(a => a.Author);
            return View(albums.ToList());
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id, int? songID)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);

            if (songID == null)
                ViewBag.songLyrics = "Click on the songin order to get it's lyrics";
            else
                ViewBag.songLyrics = db.Tracks.Find(songID).Lyrics;

            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: Albums/Create
        public ActionResult Create()
        {
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Name");
            return View();
        }

        // POST: Albums/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlbumID,AuthorID,Name,Image")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Name", album.AuthorID);
            return View(album);
        }

        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Name", album.AuthorID);
            return View(album);
        }

        // POST: Albums/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlbumID,AuthorID,Name,Image")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "Name", album.AuthorID);
            return View(album);
        }

        // GET: Albums/Delete/5

        public ActionResult Delete(int id)
        {
            if (db.Albums.Find(id) == null)
                return HttpNotFound();
            db.Albums.Remove(db.Albums.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyTestProject24/Controllers/AuthorController.cs
using MyTestProject24.DAL;
using MyTestProject24.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyTestProject24.Controllers
{
    public class AuthorController : Controller
    {
        Repository<Author> db = new Repository<Author>();
        // GET: Author

        public ActionResult Index()
        {
            return View(db.GetAll());
        }

        // GET: Author/Details/5
        public ActionResult Profile(int id)
        {
            var author = db.Get(id);
            if(author == null)
            {
                return RedirectToAction("Index","Home");
            }
            return View(author);
        }

        // GET: Author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        [HttpPost]
        public ActionResult Create(Author author)
        {
            try
            {
                db.Add(author);
                db.SaveChanges();
            }
            catch (Exception){            }

            return RedirectToAction("Index");
        }


        // GET: Author/Edit/5
        public ActionResult Edit(int id)
        {
            var author = db.Get(id);
            if(author == null)
            {
                return HttpNotFound();
            } 
            return View(author);
        }

        // POST: Author/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Author author)
        {
            try
            {
                var changeAuthor = db.Get(id);
                changeAuthor = author;
            }
            catch
            {
            }
            return RedirectToAction("Index");
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Author/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MyTestProject24/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyTestProject24.DAL;
using MyTestProject24.Models;
using System.Threading;

namespace MyTestProject24.Controllers
{
    public class AuthorsController : Controller
    {
        private UserContext db = new UserContext();
        private static int currentId;

        // GET: Authors
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,Name,Photo")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                currentId = author.AuthorID;
                Thread t = new Thread(FillAlbums);
                t.Start();
                return RedirectToAction("Profile", new { id = author.AuthorID});
            }



            return RedirectToAction("Profile", new { id = author.AuthorID });
        }


        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Profile(int id)
        {
            var author = db.Authors.Find(id);
            if (author == null) return HttpNotFound();
            if (author.Information == null)
            {
                author.Information = WebSearcher.GetArtistInformation(author.Name, 1);
                db.SaveChanges();
            }
            return View(author);
        }

        static void FillAlbums()
        {
            int id = currentId; 
            UserContext db = new UserContext();
            string authorName = db.Authors.Find(id).Name;
            List<string> authorAlbums = WebSearcher.GetAlbumsOfArtist(authorName);
            foreach(var album in authorAlbums)
            {
                Album currentAlbum = new Album();
                currentAlbum.AuthorID = id;
                currentAlbum.Name = album;
                currentAlbum.Image = WebSearcher.GetImageOfAlbum(authorName, album);

                db.Albums.Add(currentAlbum);
                db.SaveChanges();

                //IT WAS HIDDEN
                List<string> trackList = WebSearcher.GetTrackListOfAlbum(authorName, album);
                
                foreach(var track in trackList)
                {
                    Track currentTrack = new Track();
                    currentTrack.AlbumID = currentAlbum.AlbumID;
                    currentTrack.Author = db.Authors.Find(id);
                    currentTrack.Name = track;
                    currentTrack.Lyrics = WebSearcher.GetLyricsOfSong(authorName, track);
                    db.Tracks.Add(currentTrack);
                    db.SaveChanges();
                }
                //IT WAS HIDDEN
                if (db.Albums.Find(currentAlbum.AlbumID).Tracks == null)
                {
                    db.Albums.Remove(currentAlbum);
                    db.SaveChanges();
                }
            }

        }        


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyTestProject24/Views/Authors/Create.cshtml
@model MyTestProject24.Models.Author

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyTestProject24/Views/Authors/Delete.cshtml
@model MyTestProject24.Models.Author

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyTestProject24/Views/Authors/Edit.cshtml
@model MyTestProject24.Models.Author

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyTestProject24/Views/Authors/Index.cshtml
@model IEnumerable<MyTestProject24.Models.Author>

@{
    ViewBag.Title = "Index";
}

<h2>Top authors</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

            @Html.DisplayNameFor(model => model.Name)
 

    @foreach (var item in Model)
    {
        <nav class="navbar" style="box-shadow: 0px 1px 2px rgba(0,0,0,0.6)">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-1">
                        <img alt="Brand" src=@item.Photo width="64" height="64">
                    </div>
                    <div class="col-md-9">
                        <h4>
                            @Html.ActionLink(@item.Name, "Profile", new { id = item.AuthorID })
                        </h4>
                    </div>

                    <div class="col-md-2">
                            <br />
                            @Html.ActionLink(".", "Delete", new { id = item.AuthorID }, new { @class = "glyphicon glyphicon-remove-circle" })

                    </div>
                </div>
            </div>
        </nav>


    }

MyTestProject24/Views/Authors/Profile.cshtml
@model MyTestProject24.Models.Author

@{
    ViewBag.Title = Model.Name;
}


<h2>@Model.Name</h2>
<hr />





<div class="row">
    <div class="col-md-4">
        <div>

            <img src=@Model.Photo alt="Alternate Text" width="300" height="300" />
        </div>
        <div class="col-sm-4 col-md-12">
            @if (!@Model.Information.IsEmpty() && Model.Information.Length>1)
            {
                <h5>Biography</h5>
                <blockquote>
                    <p> @Model.Information  </p>
                    <small><cite title="Source Title">Wikipedia</cite></small>
                </blockquote>
            }


        </div>

    </div>
    <div class="col-md-8">
        <div class="row">

            <div>
                <div class="row">
                    @foreach (var album in Model.Albums)
                    {
                        <div class="col-sm-2 col-md-4 thumbnail">
                            <img src=@album.Image alt="..." width="204" height="204">
                            <div class="caption">
                                <nobr>
                                    <h4>
                                        @Html.ActionLink(@album.Name, "Details", "Albums",
                                                                new { id = album.AlbumID }, null)
                                    </h4>
                                </nobr>
                                <p>@album.Tracks.Count tracks</p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


<p>
    @Html.ActionLink("Back to List", "Index")
</p>